"""threshold umbenannt

Revision ID: 09209e33161f
Revises: 
Create Date: 2019-09-06 18:01:01.607413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09209e33161f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('analysis_threshold', sa.Integer(), nullable=True))
    op.drop_column('item', 'analysis_keywords_theshold')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('analysis_keywords_theshold', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('item', 'analysis_threshold')
    # ### end Alembic commands ###
