"""empty message

Revision ID: 6103d1cf3739
Revises: 81f6f2e12199
Create Date: 2019-09-18 16:17:08.447132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6103d1cf3739'
down_revision = '81f6f2e12199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('multipleupload', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'multipleupload')
    # ### end Alembic commands ###
